### ISSUE TITLE
Automatically build and post documentation, project webpage

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-extension-gem#10]
Automate the deploy docs task implemented for geojson gem

https://github.com/urbanopt/urbanopt-geojson-gem/blob/develop/deploy_docs.sh

**Comment by macumber** [comment]
Add a rake command to build docs, call that with CI.  Each repo will have to set up a gh-pages branches ahead of time?

**Comment by macumber** [comment]
Build docs for geojson gem can be seen at:

https://urbanopt.github.io/urbanopt-geojson-gem/

**Comment by macumber** [comment]
This task is to create the standard rake task

**Comment by macumber** [comment]
Add links to Readme,md's for measures

**Comment by nllong** [comment]
This has been completed correct? @tijcolem. If so, can you close?

**Comment by tijcolem** [comment]
@nllong indeed it is done.  Closing.
