### ISSUE TITLE
Can't run new test case in CLI-demo

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-extension-gem#23]
Need to either 1) move configure_osw to the runner class and remove the need to load extension gems to find measures or 2) move call to configure_osw inside the CLI after extension gems are loaded (new measure paths would show up in in.osw.out)

**Comment by macumber** [comment]
bundle_osw test case will require OpenStudio 2.8.1

**Comment by tijcolem** [comment]
Archive repo: https://github.com/NREL/openstudio-cli-demo

**Comment by nllong** [comment]
Archived: https://github.com/NREL/openstudio-cli-demo.
