### ISSUE TITLE
Save measure test dashboard to standard location

### ISSUE THREAD

**Issue by macumber** [NREL/openstudio-extension-gem#29]
Currently, running `bundle exec rake openstudio:test_with_openstudio` generates the dashboard under `\lib\measures\test_results`.  This should be in the root level so it can be picked up by CI machines.

**Comment by macumber** [comment]
The result location is not parameterized in the CLI or measure tester gem, probably best to copy to root dir here https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/runner.rb#L290

**Comment by tijcolem** [comment]
adding some logic to the ci pipeline to search for `test_results` and upload to s3 for users be able to view the dashboard.
