### ISSUE TITLE
Extend exceptions on standards error messages for curves used on multiple objects

### ISSUE THREAD

**Issue by DavidGoldwasser** [NREL/openstudio-extension-gem#95]
I want to add one more exception here for curves that are used by multiple objects which are valid but show up as an error.
https://github.com/NREL/openstudio-extension-gem/blob/develop/lib/openstudio/extension/core/os_lib_helper_methods.rb#L236

New code would be added to the end and look something like this
`(msg.logMessage.include?('[openstudio.model.Curve] This Curve, Object of type ') && msg.logMessage.include?(' has multiple parents. Returning the first.'))`

Below is an example fo the error I want to exclude
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 31' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 38' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 32' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 39' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 40' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 31' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 38' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 32' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 39' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 40' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 31' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 38' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 32' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 39' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 40' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 31' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 38' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Biquadratic' and named 'Curve Biquadratic 32' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 39' has multiple parents. Returning the first.
[openstudio.model.Curve] This Curve, Object of type 'OS:Curve:Quadratic' and named 'Curve Quadratic 40' has multiple parents. Returning the first.

**Comment by DavidGoldwasser** [comment]
@kbenne @asparke2 and @mdahlhausen are you fine with this fix unless we have different fix in standards or in core OpenStudio.

I have hit this on a number of models, including some internal projects I'm working on.

**Comment by asparke2** [comment]
yeah, suppressing these messages seems fine to me.  I think the real solution would be to fix whatever in the C++ is causing them in the first place, so probably worth filing a bug in OS so that maybe one day it will be addressed properly.
